version: "3.8"

services:
  app:
    container_name: go-command
    image: go-command
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 3000:3000